version: 2
jobs:
  build:
    working_directory: /go/src/github.com/larse514/amazonian
    docker:
      - image: circleci/golang:1.8
    # environment:
    #   - BUCKET_NAME: "moodle.sites.lambda.deployment"
    environment:
      TEST_RESULTS: /tmp/test-results
    steps:
    - checkout
    - run: mkdir -p $TEST_RESULTS

    # - restore_cache:
    #     keys:
    #       - v1-pkg-cache
    - run: go get github.com/jstemmer/go-junit-report
    - run: make dependencies
    # - run: make bindata
    - run:
        name: Run unit tests
        # environment:
        #   CONTACTS_DB_URL: "postgres://circleci-demo-go@localhost:5432/circle_test?sslmode=disable"
        #   CONTACTS_DB_MIGRATIONS: /go/src/github.com/CircleCI-Public/circleci-demo-go/db/migrations
        command: |
          trap "go-junit-report <${TEST_RESULTS}/go-test.out > ${TEST_RESULTS}/go-test-report.xml" EXIT
          make test | tee ${TEST_RESULTS}/go-test.out
          
    - run: make
    - run: 
        name: Configure AWS environment
        command: |
          aws configure set default.region us-east-1
          aws configure set default.output json
    - run:
        name: Run integration tests
        no_output_timeout: 30m
        command: |
          chmod +x integration/create_cluster_integration.sh
          ./integration/create_cluster_integration.sh
    - run:
        name: Release Binary
        command: |
          ##Note- the below is removed and has been run locally due to bug in cloudformation api not supporting no error if no changes
          # chmod +x packagemanagement/createbucket.sh
          # ./packagemanagement/createbucket.sh amazonian.package.release amazonianpackage
          make VERSION="0.0.${CIRCLE_BUILD_NUM}" release 
    - save_cache:
        key: v1-pkg-cache
        paths:
          - "/go/pkg"

    - store_artifacts:
        path: /tmp/test-results
        destination: raw-test-output

    - store_test_results:
        path: /tmp/test-results